### ISSUE TITLE
Transformer PSC crashes with Conflict error

### ISSUE THREAD

**Issue by tiredpixel** [openownership/register#228]
This month's bulk data import failed when running Transformer PSC:

```
#<Thread:0x00007f2f7f01fa30 /home/x/r/lib/register_transformer_psc/apps/transformer_bulk.rb:51 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/elasticsearch-transport-7.17.8/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [409] {"took":36,"timed_out":false,"total":9,"updated":7
,"deleted":0,"batches":1,"version_conflicts":2,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[{"index":"bods
_v2_psc_prod100","type":"_doc","id":"3041858262449778676","cause":{"type":"version_conflict_engine_exception","reason":"[3041858262449778676]: version conflict, required seqNo [15948418], pr
imary term [1]. current document has seqNo [34330998] and primary term [3]","index_uuid":"IMKKLzKRSLmAID_eGslRkg","shard":"0","index":"bods_v2_psc_prod100"},"status":409},{"index":"bods_v2_p
sc_prod100","type":"_doc","id":"742644214972504500","cause":{"type":"version_conflict_engine_exception","reason":"[742644214972504500]: version conflict, required seqNo [11512652], primary t
erm [1]. current document has seqNo [34331002] and primary term [3]","index_uuid":"IMKKLzKRSLmAID_eGslRkg","shard":"0","index":"bods_v2_psc_prod100"},"status":409}]} (Elasticsearch::Transpor
t::Transport::Errors::Conflict)                                                                                                                                                               
        from /usr/local/bundle/gems/elasticsearch-transport-7.17.8/lib/elasticsearch/transport/transport/base.rb:341:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.17.8/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.17.8/lib/elasticsearch/transport/client.rb:197:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-7.17.8/lib/elasticsearch.rb:41:in `method_missing'                      
        from /usr/local/bundle/gems/elasticsearch-api-7.17.8/lib/elasticsearch/api/actions/update_by_query.rb:88:in `update_by_query'
        from /usr/local/bundle/bundler/gems/register-sources-bods-5eeb8188e747/lib/register_sources_bods/repositories/bods_statement_repository.rb:331:in `mark_replaced_statements'
        from /usr/local/bundle/bundler/gems/register-sources-bods-5eeb8188e747/lib/register_sources_bods/services/publisher.rb:86:in `publish_new'
        from /usr/local/bundle/bundler/gems/register-sources-bods-5eeb8188e747/lib/register_sources_bods/services/publisher.rb:46:in `publish_records_with_identifiers'
        from /usr/local/bundle/bundler/gems/register-sources-bods-5eeb8188e747/lib/register_sources_bods/services/publisher.rb:33:in `publish_many'
        from /home/x/r/lib/register_transformer_psc/bods_mapping/record_processor.rb:54:in `process_many'                 
        from /home/x/r/lib/register_transformer_psc/apps/transformer_bulk.rb:82:in `process_rows'                         
        from /home/x/r/lib/register_transformer_psc/apps/transformer_bulk.rb:69:in `block in process_s3_path'             
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/services/file_reader.rb:49:in `block (2 levels) in read_from_stream'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/parsers/plain_reader.rb:7:in `each'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/parsers/plain_reader.rb:7:in `foreach'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/parsers/parser.rb:22:in `foreach'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/services/file_reader.rb:45:in `block in read_from_stream'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/decompressors/decompressor.rb:21:in `with_deflated_stream'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/services/file_reader.rb:44:in `read_from_stream'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/services/file_reader.rb:37:in `block in read_from_local_path'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/services/file_reader.rb:36:in `open'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/services/file_reader.rb:36:in `read_from_local_path'
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/services/file_reader.rb:31:in `block in read_from_s3'
        from /usr/local/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'                                                                                                                             
        from /usr/local/bundle/bundler/gems/register-common-e9b76c1caa9e/lib/register_common/services/file_reader.rb:28:in `read_from_s3'             
        from /home/x/r/lib/register_transformer_psc/apps/transformer_bulk.rb:68:in `process_s3_path'                                                  
        from /home/x/r/lib/register_transformer_psc/apps/transformer_bulk.rb:51:in `block (3 levels) in call'
```

This also happened last month. From what I recall, rerunning the Transformer PSC picked up where it failed, and the process ultimately succeeded. I've tried this again for this month's, and so far, so good.

It looks like the code is not thread-safe, and can lead to a conflict. Rather than being thread-safe or detecting this error and recovering, the entire process fails. Whilst rerunning is an acceptable workaround, this could lead to a long delay in bulk data being available, since it relies on someone detecting the hours-long process has failed and restarting it. And that assumes that it won't crash again—which, of course, it could.

This probably affects other transformers, too.

This is entirely separate to https://github.com/openownership/register/issues/213 , and wouldn't be fixed by that.

**Comment by tiredpixel** [comment]
At least in this instance, this appears to be caused by `RegisterSourcesBods::Repositories::BodsStatementRepository` `mark_replaced_statements`, which I wrote some months ago to work around BODS 0.2 non-performant replaced statements specification. I think that the conflict could also occur in other places, but I don't remember whether the other occurrences were the same.

Elasticsearch updates here are using optimistic concurrency control:

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#optimistic-concurrency-control-index

It may be that setting `retry_on_conflict` would be acceptable in our case:

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#docs-update-api-query-params

**Comment by tiredpixel** [comment]
On second thoughts, I'm not actually sure whether setting `retry_on_conflict` would be suitable.

Firstly, `mark_replaced_statements` uses `update_by_query`, which is actually this link:

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

There is an option to proceed on conflicts; however:

Secondly, what is the change being made by the other process when a document is modified concurrently? Would it lead to these statements being marked as replaced in every scenario?

I need to think more about this. It may be that fixing this is actually more complex and riskier than it's worth, especially considering as this particular error hasn't occurred in the last couple of bulk data imports (other errors have occurred, though, of course…).

**Comment by StephenAbbott** [comment]
I think your conclusion sounds sensible, @tiredpixel so I will close this as a won't fix, but keep a note of it to bear in mind for future planning
